[package]
name = "ratatoskr-instagram-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
ratatoskr-instagram-archive = { path = "../crates/instagram-archive" }

[[bin]]
name = "data_export_archive"
path = "fuzz_targets/data_export_archive.rs"
test = false
doc = false
bench = false
